info:
  contact: {}
  description: This is a sample server celler server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /getJson:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
